package com.lucasignacio.repositorioversao;

import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

public class TelaTabelaVersao extends javax.swing.JFrame {

    /**
     * Creates new form TelaTabelaVersao
     */
    public TelaTabelaVersao() {
        initComponents();
        carregarDados();
    }
    
    public void carregarDados() {
    // Obtém o modelo da sua JTable. jTableChamadosVersoes é o nome padrão dado pelo NetBeans.
    // Verifique o nome da sua variável no painel "Navegador".
    DefaultTableModel model = (DefaultTableModel) jTableChamadosVersoes.getModel();
    
    // Limpa quaisquer linhas que possam exixstir (opcional)
    model.setRowCount(0);
    
    // Adiciona a primeira linha sde dados (exemplo da sua imagem)
    model.addRow(new Object[]{
        "Estapar",
        "Americana",
        123456,
        "Atualizar Versão",
        "P:\\RepositorioVersao\\Estapar\\Americana\\Chamado#123456\\olhovivo21103.apk",
        "olhovivo21103.apk"   
    });
        
       model.addRow(new Object[]{
        "Zona Azul Brasil",
        "Cruzeiro",
        986545,
        "Teste",
        "P:\\RepositorioVersao\\Zona Azul Brasil\\Cruzeiro\\Chamado#986545\\olhovivo21902-r5.apk",
        "olhovivo21902-r5.apk"   
    });
        
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChamadosVersoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableChamadosVersoes.setAutoCreateRowSorter(true);
        jTableChamadosVersoes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTableChamadosVersoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Cidade", "Chamado", "Observação", "Caminho Arquivo", "Nome da Versão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableChamadosVersoes);
        if (jTableChamadosVersoes.getColumnModel().getColumnCount() > 0) {
            jTableChamadosVersoes.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        // Aplica o visual FlatLaf
    //   try {
     //       UIManager.setLookAndFeel(new FlatLightLaf());
    //    } catch (Exception e) {
    //        e.printStackTrace();
     //   }

        // Este bloco garante que a interface gráfica seja criada na thread correta (Event Dispatch Thread).   
     //   SwingUtilities.invokeLater(() -> {
     //       TelaTabelaVersao frame = new TelaTabelaVersao();
      //      frame.setVisible(true);
            
      //  });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableChamadosVersoes;
    // End of variables declaration//GEN-END:variables
}
